<script setup>
import { computed, onMounted, ref } from 'vue'
import { getApiError } from '../../api/client'
import { campuses, academicYears, terms, departments, classes, streams, subjects, classSubjects } from '../../api/schoolStructure'

const sections=[['overview','Overview','bi-grid-1x2'],['campuses','Campuses','bi-buildings'],['academicYears','Academic Years','bi-calendar3'],['terms','Terms','bi-calendar-range'],['departments','Departments','bi-diagram-3'],['classes','Classes','bi-collection'],['streams','Streams','bi-people'],['subjects','Subjects','bi-book'],['assignments','Class Subjects','bi-journal-check']]
const active=ref('overview'),loading=ref(true),saving=ref(false),error=ref(''),success=ref(''),editing=ref(null)
const data=ref({campuses:[],academicYears:[],terms:[],departments:[],classes:[],streams:[],subjects:[],assignments:[]}),form=ref({})
const apiMap={campuses,academicYears,terms,departments,classes,streams,subjects}
const labels={campuses:'Campus',academicYears:'Academic year',terms:'Term',departments:'Department',classes:'Class level',streams:'Stream',subjects:'Subject'}
const current=computed(()=>sections.find(x=>x[0]===active.value))
const counts=computed(()=>Object.fromEntries(Object.entries(data.value).map(([k,v])=>[k,v.length])))

function resetForm(){form.value={};editing.value=null;error.value=''}
function setSection(k){active.value=k;resetForm()}
async function load(){loading.value=true;error.value='';try{const r=await Promise.all(Object.entries(apiMap).map(async([k,v])=>[k,await v.list()]));r.forEach(([k,v])=>data.value[k]=v);data.value.assignments=await classSubjects.list()}catch(e){error.value=getApiError(e)}finally{loading.value=false}}
function editItem(item){editing.value=item.id;form.value=JSON.parse(JSON.stringify(item));error.value='';success.value='';window.scrollTo({top:0,behavior:'smooth'})}
function editAssignment(item){active.value='assignments';editItem(item)}
async function save(){saving.value=true;error.value='';success.value='';try{
  if(active.value==='assignments'){
    if(editing.value) await classSubjects.update(editing.value,{is_compulsory:!!form.value.is_compulsory})
    else await classSubjects.create({class_level_id:form.value.class_level_id,subject_id:form.value.subject_id,is_compulsory:!!form.value.is_compulsory})
  } else if(editing.value) await apiMap[active.value].update(editing.value,form.value)
  else await apiMap[active.value].create(form.value)
  resetForm();success.value=editing.value?'Updated successfully.':'Saved successfully.';await load()
}catch(e){error.value=getApiError(e)}finally{saving.value=false}}
async function removeAssignment(item){if(!confirm('Remove this subject assignment from the class?'))return;saving.value=true;try{await classSubjects.remove(item.id);success.value='Assignment removed.';await load()}catch(e){error.value=getApiError(e)}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page-wrap">
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><span class="eyebrow">SCHOOL CONFIGURATION</span><h1 class="h3 fw-bold mt-2 mb-1">School Structure</h1><p class="text-muted mb-0">Configure the academic and organisational structure used across ShuleLink.</p></div><button v-if="active!=='overview'" class="btn btn-primary" @click="resetForm"><i class="bi bi-plus-lg me-2"></i>New {{current?.[1]}}</button></div>
<div v-if="error" class="alert alert-danger">{{error}}</div><div v-if="success" class="alert alert-success">{{success}}</div>
<div class="row g-3"><aside class="col-lg-3"><div class="card border-0 shadow-sm"><div class="list-group list-group-flush"><button v-for="s in sections" :key="s[0]" class="list-group-item list-group-item-action border-0 py-3" :class="{active:active===s[0]}" @click="setSection(s[0])"><i :class="['bi',s[2],'me-2']"></i>{{s[1]}}<span v-if="s[0]!=='overview'" class="badge rounded-pill text-bg-light float-end">{{counts[s[0]]??0}}</span></button></div></div></aside>
<main class="col-lg-9"><div v-if="loading" class="card border-0 shadow-sm p-5 text-center"><span class="spinner-border"></span><div class="text-muted mt-2">Loading school structure…</div></div><template v-else>
<div v-if="active==='overview'" class="row g-3"><div v-for="s in sections.slice(1)" :key="s[0]" class="col-md-6 col-xl-4"><button class="card border-0 shadow-sm h-100 w-100 text-start p-4 section-card" @click="setSection(s[0])"><div class="icon-box mb-3"><i :class="['bi',s[2]]"></i></div><div class="fw-bold">{{s[1]}}</div><div class="text-muted small mt-1">{{counts[s[0]]||0}} configured</div></button></div></div>
<div v-else class="card border-0 shadow-sm"><div class="card-header bg-white border-0 p-4"><div class="d-flex justify-content-between align-items-start"><div><h2 class="h5 fw-bold mb-1">{{current[1]}}</h2><p class="text-muted mb-0">{{editing?'Edit the selected record.':'Add and configure '+current[1].toLowerCase()+' records for this school.'}}</p></div><button v-if="editing" class="btn btn-sm btn-outline-secondary" @click="resetForm">Cancel edit</button></div></div>
<div class="card-body p-4 border-top"><form class="row g-3 mb-4" @submit.prevent="save">
<template v-if="active==='campuses'"><div class="col-md-4"><label class="form-label">Code</label><input v-model="form.code" class="form-control" required></div><div class="col-md-8"><label class="form-label">Name</label><input v-model="form.name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Address</label><input v-model="form.address" class="form-control"></div><div class="col-md-3"><label class="form-label">Phone</label><input v-model="form.phone" class="form-control"></div><div class="col-md-3"><label class="form-label">Email</label><input v-model="form.email" type="email" class="form-control"></div><div class="col-12 form-check ms-1"><input v-model="form.is_main" class="form-check-input" type="checkbox" id="main"><label class="form-check-label" for="main">Main campus</label></div></template>
<template v-else-if="active==='academicYears'"><div class="col-md-6"><label class="form-label">Name</label><input v-model="form.name" class="form-control" placeholder="2026 Academic Year" required></div><div class="col-md-3"><label class="form-label">Start</label><input v-model="form.start_date" type="date" class="form-control" required></div><div class="col-md-3"><label class="form-label">End</label><input v-model="form.end_date" type="date" class="form-control" required></div><div class="col-12 form-check ms-1"><input v-model="form.is_current" class="form-check-input" type="checkbox" id="yc"><label class="form-check-label" for="yc">Current academic year</label></div></template>
<template v-else-if="active==='terms'"><div class="col-md-6"><label class="form-label">Academic year</label><select v-model="form.academic_year_id" class="form-select" required><option value="" disabled>Select year</option><option v-for="x in data.academicYears" :key="x.id" :value="x.id">{{x.name}}</option></select></div><div class="col-md-3"><label class="form-label">Term number</label><input v-model.number="form.term_number" type="number" min="1" max="4" class="form-control" required></div><div class="col-md-3"><label class="form-label">Name</label><input v-model="form.name" class="form-control" placeholder="Term 1" required></div><div class="col-md-6"><label class="form-label">Start</label><input v-model="form.start_date" type="date" class="form-control" required></div><div class="col-md-6"><label class="form-label">End</label><input v-model="form.end_date" type="date" class="form-control" required></div><div class="col-12 form-check ms-1"><input v-model="form.is_current" class="form-check-input" type="checkbox" id="tc"><label class="form-check-label" for="tc">Current academic term</label></div></template>
<template v-else-if="active==='departments'"><div class="col-md-4"><label class="form-label">Code</label><input v-model="form.code" class="form-control" required></div><div class="col-md-8"><label class="form-label">Name</label><input v-model="form.name" class="form-control" required></div><div class="col-12"><label class="form-label">Description</label><textarea v-model="form.description" class="form-control" rows="2"></textarea></div></template>
<template v-else-if="active==='classes'"><div class="col-md-4"><label class="form-label">Code</label><input v-model="form.code" class="form-control" placeholder="G7" required></div><div class="col-md-6"><label class="form-label">Class name</label><input v-model="form.name" class="form-control" placeholder="Grade 7" required></div><div class="col-md-2"><label class="form-label">Order</label><input v-model.number="form.level_order" type="number" class="form-control"></div></template>
<template v-else-if="active==='streams'"><div class="col-md-6"><label class="form-label">Class level</label><select v-model="form.class_level_id" class="form-select" required><option value="" disabled>Select class</option><option v-for="x in data.classes" :key="x.id" :value="x.id">{{x.name}}</option></select></div><div class="col-md-3"><label class="form-label">Code</label><input v-model="form.code" class="form-control" placeholder="A" required></div><div class="col-md-3"><label class="form-label">Name</label><input v-model="form.name" class="form-control" placeholder="Stream A" required></div><div class="col-md-3"><label class="form-label">Capacity</label><input v-model.number="form.capacity" type="number" min="1" class="form-control"></div></template>
<template v-else-if="active==='subjects'"><div class="col-md-3"><label class="form-label">Code</label><input v-model="form.code" class="form-control" placeholder="ENG" required></div><div class="col-md-5"><label class="form-label">Subject</label><input v-model="form.name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Department</label><select v-model="form.department_id" class="form-select"><option :value="null">None</option><option v-for="x in data.departments" :key="x.id" :value="x.id">{{x.name}}</option></select></div><div class="col-md-4"><label class="form-label">Short name</label><input v-model="form.short_name" class="form-control"></div><div class="col-md-4"><label class="form-label">Type</label><select v-model="form.subject_type" class="form-select"><option value="core">Core</option><option value="elective">Elective</option><option value="co_curricular">Co-curricular</option></select></div></template>
<template v-else><div v-if="!editing" class="col-md-6"><label class="form-label">Class level</label><select v-model="form.class_level_id" class="form-select" required><option value="" disabled>Select class</option><option v-for="x in data.classes" :key="x.id" :value="x.id">{{x.name}}</option></select></div><div v-if="!editing" class="col-md-6"><label class="form-label">Subject</label><select v-model="form.subject_id" class="form-select" required><option value="" disabled>Select subject</option><option v-for="x in data.subjects" :key="x.id" :value="x.id">{{x.name}}</option></select></div><div v-if="editing" class="col-12"><div class="alert alert-light border mb-0">{{data.assignments.find(x=>x.id===editing)?.class_name}} → {{data.assignments.find(x=>x.id===editing)?.subject_name}}</div></div><div class="col-12 form-check ms-1"><input v-model="form.is_compulsory" class="form-check-input" type="checkbox" id="comp"><label class="form-check-label" for="comp">Compulsory subject</label></div></template>
<div class="col-12"><button class="btn btn-primary" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm me-2"></span>{{saving?(editing?'Updating…':'Saving…'):(editing?'Update':'Save')}}</button></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th v-if="['campuses','departments','classes','subjects'].includes(active)">Code</th><th v-if="active==='academicYears'">Period</th><th v-if="active==='terms'">Year</th><th v-if="active==='terms'">Period</th><th v-if="active==='streams'">Class</th><th v-if="active==='assignments'">Subject</th><th v-if="active==='assignments'">Compulsory</th><th class="text-end">Actions</th></tr></thead><tbody>
<tr v-for="x in (active==='assignments'?data.assignments:data[active])" :key="x.id"><td><strong v-if="active==='assignments'">{{x.class_name}}</strong><strong v-else>{{x.name}}</strong><span v-if="active==='terms'" class="badge text-bg-light ms-2">Term {{x.term_number}}</span><span v-if="active==='academicYears'&&x.is_current" class="badge text-bg-success ms-2">Current</span><span v-if="active==='terms'&&x.is_current" class="badge text-bg-success ms-2">Current</span></td><td v-if="['campuses','departments','classes','subjects'].includes(active)">{{x.code}}</td><td v-if="active==='academicYears'">{{x.start_date}} → {{x.end_date}}</td><td v-if="active==='terms'">{{data.academicYears.find(y=>y.id===x.academic_year_id)?.name||'—'}}</td><td v-if="active==='terms'">{{x.start_date}} → {{x.end_date}}</td><td v-if="active==='streams'">{{data.classes.find(c=>c.id===x.class_level_id)?.name||'—'}}</td><td v-if="active==='assignments'">{{x.subject_name}}</td><td v-if="active==='assignments'"><span :class="x.is_compulsory?'text-success':'text-muted'">{{x.is_compulsory?'Yes':'No'}}</span></td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-primary me-1" @click="active==='assignments'?editAssignment(x):editItem(x)"><i class="bi bi-pencil"></i></button><button v-if="active==='assignments'" class="btn btn-sm btn-outline-danger" @click="removeAssignment(x)"><i class="bi bi-trash"></i></button></td></tr><tr v-if="!(active==='assignments'?data.assignments:data[active]).length"><td colspan="9" class="text-center text-muted py-4">Nothing configured yet.</td></tr></tbody></table></div>
</div></div></template></main></div></div></template>
