<script setup>
import { computed, onMounted, ref } from "vue";
import { tenantContext } from "../../api/tenants";
import { getApiError } from "../../api/client";
import { useAuthStore } from "../../stores/auth";
const auth=useAuthStore(),context=ref(null),loading=ref(true),error=ref("");const hostname=computed(()=>window.location.hostname);
onMounted(async()=>{try{context.value=await tenantContext()}catch(e){error.value=getApiError(e)}finally{loading.value=false}})
</script>
<template><div class="page-wrap"><div v-if="loading" class="py-5 text-center"><span class="spinner-border"></span></div><template v-else><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><span class="eyebrow">SCHOOL PORTAL</span><h1 class="h3 fw-bold mt-2 mb-1">Welcome, {{auth.user?.first_name}}</h1><p class="text-muted mb-0">Manage your school's day-to-day workspace.</p></div><router-link to="/school/structure" class="btn btn-primary"><i class="bi bi-diagram-3 me-2"></i>School Structure</router-link></div><div v-if="error" class="alert alert-danger">{{error}}</div><div class="row g-3 mb-4"><div class="col-md-4"><div class="stat-card"><div class="icon-box"><i class="bi bi-building"></i></div><div><div class="text-muted small">School</div><div class="fw-bold">{{context?.name||'Connected'}}</div></div></div></div><div class="col-md-4"><div class="stat-card"><div class="icon-box"><i class="bi bi-person-badge"></i></div><div><div class="text-muted small">Signed in as</div><div class="fw-bold text-truncate">{{auth.user?.email}}</div></div></div></div><div class="col-md-4"><div class="stat-card"><div class="icon-box"><i class="bi bi-globe2"></i></div><div><div class="text-muted small">School host</div><div class="fw-bold">{{hostname}}</div></div></div></div></div><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 fw-bold">School administration</h2><p class="text-muted mb-3">Start by configuring campuses, academic years, terms, classes, streams, departments and subjects. These foundations will power the student and academic modules.</p><router-link to="/school/structure" class="btn btn-outline-primary">Configure structure <i class="bi bi-arrow-right ms-1"></i></router-link></div></div></template></div></template>
